import Canvas from '../components/Canvas';
import Head from 'next/head'
import Image from 'next/image'
import css from '../styles/Home.module.css';
import Box from './canvas/box';
import Floor from './canvas/floor';
import LightBulb from './canvas/lightBulb';
import OrbitControls from '../components/OrbitControls'
import Draggable from '../components/Draggable'
import Career from '../components/page/Career';
import Profile from '../components/page/Profile';
import Project from '../components/page/Project';
import Skill from '../components/page/Skill';
import Intro from '../components/page/intro/intro';
import TopNavigationBar from '../components/header/TopNavigationBar';


export default function Home(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Siniz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <TopNavigationBar/>
      </header>

      <main className={'bg-slate-100 min-h-screen flex-row'}>
        <Intro />
        <Skill />
        <Profile />
        <Project />
        <Career />

      </main>

    </div>
  )
}
