import Head from 'next/head'
import css from '../styles/Home.module.css';
import Intro from '../components/page/intro/intro';
import Profile from "../components/page/Profile";
import Skill from "../components/page/Skill";
import Project from "../components/page/Project";
import Career from "../components/page/Career";
import TopNavigationBar from "../components/header/TopNavigationBar";


export default function Home(): JSX.Element {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={'bg-slate-100 grid gap-10 min-h-screen'}>
                <TopNavigationBar/>

                <div className={css.scene}>
                    <Intro/>
                    <Profile/>
                    <Skill/>
                    <Project/>
                    <Career/>

                </div>
            </main>

        </div>
    )
}
